### PR TITLE
Add custom http.Client support

### PR DESCRIPTION
**Pull request by tdakkota**
- Adds new struct`ScriptConfig`, like `BotConfig`
- Adds Client field to `BotConfig`
- Patches `clientConfig.Client` if it is not nil

### CODE REVIEW

**Comment by turnage** [comment]
You can specify a custom `http.Client` in this code, but the `Transport` is overwritten. What in particular do you want to override about the `http.Client`? Perhaps that would be better to define in the config specifically.

**Comment by turnage** [comment]
Thank you for writing a PR!

**Comment by turnage** [comment]
Reverted because this broke users.

Forgive me that I did not catch this in review. Thankfully @iwinulose filed a bug report promptly.

I will re-review if you add tests.

**Comment by tdakkota** [comment]
Should I make a new PR?

**Comment by turnage** [comment]
Yes I don’t believe a closed PR can receive updates.

**Pull request merged**
